language: python

os: linux

compiler: gcc

python:
    - "3.6"

install:
    - pip install pybind11
    - pip install pytest
    - python3 -m pybind11 --includes
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_CXX_FLAGS="`python -m pybind11 --includes`"
    - make
    - sudo make install
    - export PYTHONPATH=$PYTHONPATH:/usr/local/lib
    - cd ..

script:
    - x2z examples/ch4.xyz
    - pytest -v
